export default new Map([
    ['Animation', 'animation'],
    ['Channels', 'animation/channels'],
    ['ColorType', 'https://github.com/gitpushjoe/sharc/blob/main/src/sharc/types/Common.ts#L6'],
    ['PositionType', 'https://github.com/gitpushjoe/sharc/blob/main/src/sharc/types/Common.ts#L1'],
    ['Working with the Animation Loop', 'stage/working-with-the-animation-loop'],
    ['canvas unit', 'getting-started/terminology/canvas-unit'],
    ['canvas units', 'getting-started/terminology/canvas-unit'],
    ['bounds', 'getting-started/terminology/bounds'],
    ['animation channels', 'animation/channels'],
    ['Line', 'sprites/line'],
    ['BezierCurve', 'sprites/beziercurve'],
    ['Path', 'sprites/path'],
    ['Polygon', 'sprites/polygon'],
    ['Ellipse', 'sprites/ellipse'],
    ['LabelSprite', 'sprites/label'],
    ['TextSprite', 'sprites/text'],
    ['Text', 'sprites/text'],
    ['Stage', 'stage'],
    ['Sprites', 'sprites'],
    ['Sprite', 'sprites'],
    ['NullSprite', 'sprites/nullsprite'],
    ['Sprites/Properties', 'sprites/properties'],
    ['Types/Animation/AnimationPackage', 'types/animation/animationpackage'],
    ['Types/Animation/AnimationType', 'types/animation/animationtype'],
    ['Types/Animation/AnimationParams', 'types/animation/animationparams'],
    ['Sprites/Parenting', 'sprites/parenting'],
    ['animation', 'animation'],
    ['universal sprite properties', 'sprites/properties/universal-sprite-properties'],
    ['AnimationUtils', 'utils/animation'],
    ['BoundsType', 'https://github.com/gitpushjoe/sharc/blob/main/src/sharc/types/Common.ts#L13'],
    ['ArrowType', 'https://github.com/gitpushjoe/sharc/blob/main/src/sharc/types/Sprites.ts#L84'],
    ['StrokeType', 'https://github.com/gitpushjoe/sharc/blob/main/src/sharc/types/Sprites.ts#L74'],
    ['RadiusType', 'https://github.com/gitpushjoe/sharc/blob/main/src/sharc/types/Sprites.ts#L146'],
    ['StrokeableSprite', 'sprites/strokeablesprite'],
    ['Rect', 'sprites/rect'],
    ['Star', 'sprites/star'],
    ['Image', 'sprites/image'],
    ['Sprite/Details', 'sprites/details'],
    ['TextProperties', 'https://github.com/gitpushjoe/sharc/blob/main/src/sharc/types/Sprites.ts#L221'],
    ['AnimationType', 'https://github.com/gitpushjoe/sharc/blob/main/src/sharc/types/Animation.ts#L23'],
    ['AnimationPackage', 'https://github.com/gitpushjoe/sharc/blob/main/src/sharc/types/Animation.ts#L45'],
]);
