export default new Map([
    ['Animation', 'animation'],
    ['Channels', 'animation/channels'],
    ['ColorType', 'types/common/colortype'],
    ['PositionType', 'types/common/positiontype'],
    ['Working with the Animation Loop', 'stage/working-with-the-animation-loop'],
    ['canvas unit', 'getting-started/terminology/canvas-unit'],
    ['canvas units', 'getting-started/terminology/canvas-unit'],
    ['bounds', 'getting-started/terminology/bounds'],
    ['animation channels', 'animation/channels'],
    ['BezierCurve', 'sprites/beziercurve'],
    ['Path', 'sprites/path'],
    ['Polygon', 'sprites/polygon'],
    ['Ellipse', 'sprites/ellipse'],
    ['LabelSprite', 'sprites/label'],
    ['TextSprite', 'sprites/text'],
    ['Text', 'sprites/text'],
    ['Stage', 'stage'],
    ['Sprites', 'sprites'],
    ['Sprite', 'sprites'],
    ['Sprites/Properties', 'sprites/properties'],
    ['Types/Animation/AnimationPackage', 'types/animation/animationpackage'],
    ['Types/Animation/AnimationType', 'types/animation/animationtype'],
    ['Types/Animation/AnimationParams', 'types/animation/animationparams'],
    ['Sprites/Parenting', 'sprites/parenting'],
    ['animation', 'animation'],
    ['universal sprite properties', 'sprites/properties/universal-sprite-properties'],
])